spring:
  application:
    name: exampleRedisKa

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:rediska;CACHE_SIZE=0
    driver-class-name: org.h2.Driver
    username: admin
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
